# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{failurous-rails}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mikko Nyl\303\251n", "Tero Parviainen", "Antti Forsell"]
  s.date = %q{2010-11-03}
  s.description = %q{failurous-rails is a Rails notifier for sending notifications to Failurous from Ruby on Rails applications}
  s.files = [
    ".gitignore",
     "VERSION",
     "lib/failurous/rails.rb",
     "lib/failurous/rails/config.rb",
     "lib/failurous/rails/fail_middleware.rb",
     "lib/failurous/rails/fail_notification.rb",
     "spec/fail_notification_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mnylen/failurous-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails notifier for Failurous}
  s.test_files = [
    "spec/fail_notification_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

